version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        WORKDIR:               $WORKDIR
        HOST:                  $HOST
        BACKEND_PORT:          $BACKEND_PORT
        DB_HOST:               $DB_HOST
        DB_NAME:               $DB_NAME
        DB_USERNAME:           $DB_USERNAME
        DB_PASSWORD:           $DB_PASSWORD
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b ${HOST}"
    volumes:
      - ./backend:/$WORKDIR
      - backend-bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "$BACKEND_PORT:3000"
    # environment:
    #   RAILS_ENV: "production"

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR:           $WORKDIR
        HOST:              $HOST
        FRONTEND_PORT:        $FRONTEND_PORT
        BACKEND_BASE_URL:  $BACKEND_BASE_URL
        BROWSER_BASE_URL:  $BROWSER_BASE_URL
    command: npm run serve
    volumes:
      - ./frontend:/$WORKDIR
      - frontend-node_modules:/app/node_modules
    ports:
      - "$FRONTEND_PORT:8080"
    depends_on:
      - backend
  #   # environment:
  #   #   NODE_ENV: "production"

volumes:
  db-data:
  backend-bundle:
  frontend-node_modules: