source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '~> 6.1.3.1'
gem 'kaminari'
gem 'active_model_serializers'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 5.2.2'
gem 'aws-sdk-s3', require: false
gem 'bootsnap', require: false
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
  gem 'pry-rails'
  gem 'shoulda-matchers'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'rubocop', require:false
  gem 'rubocop-rails', require:false
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
